# ??? DATABASE (LOCAL) ???
spring.datasource.url=jdbc:postgresql://localhost:5432/buildpos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ??? DEV SOZLAMALAR ???
spring.jpa.show-sql=true
logging.level.com.buildpos=DEBUG

# ??? JWT ???
jwt.secret=buildpos-secret-key-2025-very-long-string-for-security
jwt.expiration=86400000